In [7]:
import pandas as pd 

df = pd.read_csv("productOrders.csv")

In [8]:
df.head() # returns first 5 rows of dataframe

,order_id,CustomerName,product_name,category_name,quantity,list_price,order_date,order_status,state
0,1,Johnathan Velazquez,Electra Townie Original 7D EQ - Women's - 2016,Cruisers Bicycles,1,599.99,1/1/2016,4,CA
1,1,Johnathan Velazquez,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,2,1799.99,1/1/2016,4,CA
2,1,Johnathan Velazquez,Surly Straggler - 2016,Cyclocross Bicycles,2,1549.00,1/1/2016,4,CA
3,1,Johnathan Velazquez,Electra Townie Original 7D EQ - 2016,Cruisers Bicycles,2,599.99,1/1/2016,4,CA
4,1,Johnathan Velazquez,Trek Fuel EX 8 29 - 2016,Mountain Bikes,1,2899.99,1/1/2016,4,CA

In [9]:
df.tail() # returns last 5 rows of dataframe

,order_id,CustomerName,product_name,category_name,quantity,list_price,order_date,order_status,state
95,32,Kimbery Nieves,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,2,1799.99,1/21/2016,4,CA
96,32,Kimbery Nieves,Electra Townie Original 21D - 2016,Cruisers Bicycles,2,549.99,1/21/2016,4,CA
97,32,Kimbery Nieves,Electra Townie Original 7D - 2015/2016,Comfort Bicycles,2,499.99,1/21/2016,4,CA
98,33,Verona O'neill,Electra Girl's Hawaii 1 (20-inch) - 2015/2016,Children Bicycles,2,299.99,1/21/2016,4,NY
99,33,Verona O'neill,Trek Slash 8 27.5 - 2016,Mountain Bikes,1,3999.99,1/21/2016,4,NY

In [10]:
df.info() # prints concise summary of dataframe including index dtype and columns, non-null values and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       100 non-null    int64
 1   CustomerName   100 non-null    object
 2   product_name   100 non-null    object
 3   category_name  100 non-null    object
 4   quantity       100 non-null    int64
 5   list_price     100 non-null    float64
 6   order_date     100 non-null    object
 7   order_status   100 non-null    int64
 8   state          100 non-null    object
dtypes: float64(1), int64(3), object(5)
memory usage: 7.2+ KB

In [11]:
df.describe() # returns statistical summary for columns in dataframe

         order_id    quantity   list_price  order_status
count  100.000000  100.000000   100.000000         100.0
mean    17.950000    1.490000  1132.381600           4.0
std      9.572029    0.502418  1079.034179           0.0
min      1.000000    1.000000   269.990000           4.0
25%     10.750000    1.000000   429.000000           4.0
50%     18.000000    1.000000   599.990000           4.0
75%     26.250000    2.000000  1581.997500           4.0
max     33.000000    2.000000  3999.990000           4.0

In [12]:
df.columns # returns the column labels of the dataframe

Index(['order_id', 'CustomerName', 'product_name', 'category_name', 'quantity',
       'list_price', 'order_date', 'order_status', 'state'],
      dtype='object')

In [13]:
df.index # returns the index (row labels) of the dataframe

RangeIndex(start=0, stop=100, step=1)

In [14]:
len(df["state"]), set(df["state"]) # returns the number of row and unique values in the "state" column

(100, {'CA', 'NY', 'TX'})

In [15]:
df[["CustomerName","category_name"]] # index by Series of the columns

           CustomerName        category_name
0   Johnathan Velazquez    Cruisers Bicycles
1   Johnathan Velazquez       Mountain Bikes
2   Johnathan Velazquez  Cyclocross Bicycles
3   Johnathan Velazquez    Cruisers Bicycles
4   Johnathan Velazquez       Mountain Bikes
..                  ...                  ...
95       Kimbery Nieves       Mountain Bikes
96       Kimbery Nieves    Cruisers Bicycles
97       Kimbery Nieves     Comfort Bicycles
98       Verona O'neill    Children Bicycles
99       Verona O'neill       Mountain Bikes

[100 rows x 2 columns]

In [16]:
import pandas as pd

data_list = ['p', 'y', 't', 'h', 'o', 'n'] # create a list of characters
ser = pd.Series(data_list) # create a pandas Series from a list
print(ser)

0    p
1    y
2    t
3    h
4    o
5    n
dtype: object

In [17]:
data_dict = {'pandas_1': 'p', 'pandas_2': 'y', 'pandas_3': 't', 'pandas_4': 'h', 'pandas_5': 'o', 'pandas_6': 'n'} # create a dictionary of characters
ser2 = pd.Series(data_dict) # create a pandas Series from a dictionary, which the keys become the index labels and the values become the data
print(ser2)

pandas_1    p
pandas_2    y
pandas_3    t
pandas_4    h
pandas_5    o
pandas_6    n
dtype: object

In [18]:
df.iloc[34] # index by location of the row using dataframe iloc indexer

order_id                                            14
CustomerName                           Maribel William
product_name     Surly Ice Cream Truck Frameset - 2016
category_name                           Mountain Bikes
quantity                                             1
list_price                                      469.99
order_date                                    1/9/2016
order_status                                         4
state                                               CA
Name: 34, dtype: object

In [20]:
df[(df["category_name"]== "Mountain Bikes") & (df["state"]== "CA")] # create a filter in my data frame where the column category is equal to "Mountain Bikes"

,order_id,CustomerName,product_name,category_name,quantity,list_price,order_date,order_status,state
1,1,Johnathan Velazquez,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,2,1799.99,1/1/2016,4,CA
4,1,Johnathan Velazquez,Trek Fuel EX 8 29 - 2016,Mountain Bikes,1,2899.99,1/1/2016,4,CA
9,4,Nova Hess,Ritchey Timberwolf Frameset - 2016,Mountain Bikes,2,749.99,1/3/2016,4,CA
23,9,Neil Mccall,Trek Slash 8 27.5 - 2016,Mountain Bikes,2,3999.99,1/5/2016,4,CA
28,12,Marvin Mullins,Trek Fuel EX 8 29 - 2016,Mountain Bikes,2,2899.99,1/6/2016,4,CA
34,14,Maribel William,Surly Ice Cream Truck Frameset - 2016,Mountain Bikes,1,469.99,1/9/2016,4,CA
39,16,Lea Key,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,1,1799.99,1/12/2016,4,CA
43,17,Sindy Anderson,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,1,1799.99,1/12/2016,4,CA
45,17,Sindy Anderson,Heller Shagamaw Frame - 2016,Mountain Bikes,1,1320.99,1/12/2016,4,CA
47,18,Lanita Burton,Ritchey Timberwolf Frameset - 2016,Mountain Bikes,2,749.99,1/14/2016,4,CA
49,18,Lanita Burton,Trek Slash 8 27.5 - 2016,Mountain Bikes,1,3999.99,1/14/2016,4,CA
61,23,Drucilla Gilliam,Trek Fuel EX 8 29 - 2016,Mountain Bikes,2,2899.99,1/16/2016,4,CA
95,32,Kimbery Nieves,Trek Remedy 29 Carbon Frameset - 2016,Mountain Bikes,2,1799.99,1/21/2016,4,CA

In [21]:
df[df["quantity"] > 3] # conditional filtering based on columns using a dataframe column

Empty DataFrame
Columns: [order_id, CustomerName, product_name, category_name, quantity, list_price, order_date, order_status, state]
Index: []

In [30]:
df[df["product_name"].str.startswith("H")] # filtering based on string methods using a dataframe columns

,order_id,CustomerName,product_name,category_name,quantity,list_price,order_date,order_status,state
45,17,Sindy Anderson,Heller Shagamaw Frame - 2016,Mountain Bikes,1,1320.99,1/12/2016,4,CA
75,27,Pamala Henry,Heller Shagamaw Frame - 2016,Mountain Bikes,1,1320.99,1/19/2016,4,NY
79,28,Eleni Gordon,Heller Shagamaw Frame - 2016,Mountain Bikes,1,1320.99,1/19/2016,4,NY

In [25]:
unique_state = df["state"].unique() # filtering based on unique values in a dataframe column
print(unique_state)

['CA' 'NY' 'TX']

In [ ]:
df.loc[df['CustomerName'] == 'Sindy Anderson', 'quantity'] = 10 # locate specific value in dataframe and update it

In [ ]:
df = df.drop_duplicates() # drop duplicate rows from dataframe

In [ ]:
df = df.drop(2) # drop row with index label 2 from dataframe

In [ ]:
df.groupby("category_name")["list_price"].sum() # grouping by a column and aggregating another column using sum function

category_name
Children Bicycles       3929.86
Comfort Bicycles        3349.94
Cruisers Bicycles      16679.74
Cyclocross Bicycles    12655.98
Electric Bikes         14999.95
Mountain Bikes         61622.69
Name: list_price, dtype: float64

In [ ]:
df.to_csv("updated_productOrders.csv", index=False) # export dataframe to a new CSV file without the index